#!/usr/bin/env bash
# sh script that transfers a file from our client to a server

# Check if all parameters are found
if [ $# -lt 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

# Assgin Vars
file_path=$1
ip=$2
username=$3
ssh_path=$4

# Transfere the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username@$ip:~/"
