#!/usr/bin/env bash
# Install nginx listen on port 80

# Update packages and install nginx
apt-get -y update
apt-get -y install nginx

# Listen to the port 80
echo "server {
      listen 80 default_server;
      listen [::]:80 default_server;
      root /var/www/html;
      index index.html;
      server_name _;
      location / {
          return 200 'Hello World!';
      }
}"

# Start service
service nginx start
