#!/usr/bin/env bash
# Install nginx listen on port 80

# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Listen to the port 80
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Start service
sudo service nginx start
