#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name,
# of processes whose name contain the word bash.

processes=$(pgrep -f bash)

for process in $processes; do
	echo $process bash
done
