#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0

while ((i < 13)); do
	echo Hour: $i
	for ((j = 1; j < 60; j++)); do
		echo $j
	done
	((i++))
done
