#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server

# update the hosts files
cp /etc/hosts ~/hosts.new

sed -i 's/^127.0.0.2 localhost*$//' ~/hosts.new
sed -i 's/^8.8.8.8 facebook.com*$//' ~/hosts.new

echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
