#!/usr/bin/env bash
# Bash script that configures the container to fit
# nginx must be running as nginx user &listening on all active IPs on port 8080

pkill apache2
sed -i "s/\s*#?\s*user .*/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service nginx start
